name: 24/7 Movie Bot
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install pyTelegramBotAPI requests
      - name: Run Bot
        run: python bot.py
